name: Deploy to AWS

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # This is required for requesting the JWT token used to authenticate to AWS

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ######
      # Build
      ######
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm ci
      - name: Build
        env:
          URL_PREFIX: https://painting-tools.owlbear.davidsev.co.uk/${{ github.ref_name }}
        run: npm run prod
      ######
      # Login to AWS
      ######
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-west-2
          role-session-name: Github
      ######
      # Push to s3
      ######
      - name: Deploy to S3
        run: |
          aws s3 sync --metadata-directive REPLACE --cache-control "public, max-age=604800, immutable" ./dist "s3://${{ secrets.S3_BUCKET }}/${{ github.ref_name }}" --delete
          aws s3 cp --metadata-directive REPLACE --cache-control 'public, max-age=300' ./dist/manifest.json "s3://${{ secrets.S3_BUCKET }}/"
          aws s3 cp --metadata-directive REPLACE --cache-control 'public, max-age=3600' --recursive ./static_root/ "s3://${{ secrets.S3_BUCKET }}/"
